Repository mautic-inc/plugin-integrations, pull requests merged in 2019-09, with the labels that each got.

#47 Add MauticSyncFieldsLoadEvent
  Config/config.php
  Event/MauticSyncFieldsLoadEvent.php
  IntegrationEvents.php
  Sync/SyncDataExchange/Helper/FieldHelper.php
  Tests/Event/MauticSyncFieldsLoadEventTest.php
  Tests/Sync/SyncDataExchange/Helper/FieldHelperTest.php
Labels: Code Review

#46 Fixes for bi-directional DNC Salesforce sync
  Sync/Helper/MappingHelper.php
  Sync/SyncDataExchange/MauticSyncDataExchange.php
  Sync/SyncProcess/Direction/Internal/ObjectChangeGenerator.php
Labels: Bug, Pending feedback

#48 Maut 21 - Sync specific objects
  Command/SyncCommand.php
  Config/config.php
  Exception/InvalidValueException.php
  README.md
  Sync/DAO/Sync/InputOptionsDAO.php
  Sync/DAO/Sync/ObjectIdsDAO.php
  Sync/DAO/Sync/Request/RequestDAO.php
  Sync/SyncDataExchange/Internal/ReportBuilder/FullObjectReportBuilder.php
  Sync/SyncDataExchange/MauticSyncDataExchange.php
  Sync/SyncProcess/Direction/Integration/IntegrationSyncProcess.php
  Sync/SyncProcess/Direction/Internal/MauticSyncProcess.php
  Sync/SyncProcess/SyncProcess.php
  Sync/SyncProcess/SyncProcessFactory.php
  Sync/SyncProcess/SyncProcessFactoryInterface.php
  Sync/SyncService/SyncService.php
  Sync/SyncService/SyncServiceInterface.php
  Tests/Command/SyncCommandTest.php
  Tests/EventListener/LeadSubscriberTest.php
  Tests/Sync/DAO/InputOptionsDAOTest.php
  Tests/Sync/DAO/ObjectIdsDAOTest.php
  Tests/Sync/SyncDataExchange/Internal/ReportBuilder/FullObjectReportBuilderTest.php
  Tests/Sync/SyncDataExchange/Internal/ReportBuilder/PartialObjectReportBuilderTest.php
  Tests/Sync/SyncProcess/Direction/Integration/IntegrationSyncProcessTest.php
  Tests/Sync/SyncProcess/Direction/Internal/MauticSyncProcessTest.php
Labels: Code Review

#52 MAUT-2811 add migration engine
  Bundle/AbstractPluginBundle.php
  Config/config.php
  Exception/PathNotFoundException.php
  IntegrationsBundle.php
  Migration/AbstractMigration.php
  Migration/Engine.php
  Migration/MigrationInterface.php
  Migrations/Version_0_0_1.php
Labels: Code Review, Community

#55 Allow deleting array of ids in mapping, MAUT-2705
  Entity/ObjectMappingRepository.php
Labels: Code Review, Community

#50 Add reference_id to object mapping entity, add indexes
  Entity/ObjectMapping.php
  Exception/IntegrationMappingException.php
  Tests/Entity/ObjectMappingTest.php
  composer.json
  composer.lock
  phpunit.xml
Labels: Code Review, Community
